# Generated by Django 3.1 on 2020-08-27 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20200826_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='datecompleted',
            new_name='date_completed',
        ),
    ]
